todo/todo/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('create/', views.create_user, name='create_user'),
    path('<int:user_id>/', views.view_user, name='view_user'),
    path('<int:user_id>/update/', views.update_user, name='update_user'),
    path('<int:user_id>/delete/', views.delete_user, name='delete_user'),
]

todo/todo/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name

todo/todo/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email']

todo/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import UserForm

def user_list(request):
    users = User.objects.all()
    return render(request, 'templates/user_list.html', {'users': users})

def create_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('templates:user_list')
    else:
        form = UserForm()
    return render(request, 'templates/create_user.html', {'form': form})

def view_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'templates/view_user.html', {'user': user})

def update_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    form = UserForm(instance=user)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:view_user', user_id=user_id)
    return render(request, 'templates/update_user.html', {'form': form, 'user': user})

def delete_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('templates:user_list')
    return render(request, 'templates/delete_user.html', {'user': user})

todo/todo/templates/create_user.html
<h1>Create User</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
<a href="{% url 'users:user_list' %}">Back to User List</a>

todo/todo/templates/delete_user.html
<h1>Delete User</h1>
<p>Are you sure you want to delete user '{{ user.name }}'?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
<a href="{% url 'users:view_user' user.id %}">Cancel</a>

todo/todo/templates/update_user.html
<h1>Edit User</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
<a href="{% url 'users:view_user' user.id %}">Cancel</a>

todo/todo/templates/user_list.html
<!-- Display a list of users -->
<h1>User List</h1>
<ul>
    {% for user in users %}
        <li><a href="{% url 'users:view_user' user.id %}">{{ user.name }}</a></li>
    {% endfor %}
</ul>
<a href="{% url 'users:create_user' %}">Create User</a>

todo/todo/templates/view_user.html
<h1>User Information</h1>
<p>ID: {{ user.id }}</p>
<p>Name: {{ user.name }}</p>
<p>Email: {{ user.email }}</p>
<a href="{% url 'users:update_user' user.id %}">Edit</a>
<a href="{% url 'users:delete_user' user.id %}">Delete</a>
<a href="{% url 'users:user_list' %}">Back to User List</a>